# Generated by Django 3.0.6 on 2020-08-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='cover',
        ),
    ]
