# Generated by Django 3.0.6 on 2020-08-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_size',
        ),
    ]
