# Generated by Django 3.0.6 on 2020-09-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_box_box_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='s',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
