# Generated by Django 3.0.6 on 2020-09-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
