# Generated by Django 3.0.6 on 2020-09-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_box_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='year_in_school',
            field=models.CharField(choices=[(1, 'Freshman'), (11, 'Sophomore'), (111, 'Junior'), (1111, 'Senior')], default=1, max_length=2),
        ),
    ]
