# Generated by Django 3.0.6 on 2020-09-08 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20200908_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='year_in_school',
        ),
    ]
