# Generated by Django 3.0.6 on 2020-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_box_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='slug',
        ),
        migrations.AddField(
            model_name='post1',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
