# Generated by Django 3.0.6 on 2020-09-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='Field',
        ),
    ]
