# Generated by Django 3.0.6 on 2020-09-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20200910_1309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
