# Generated by Django 3.0.6 on 2020-09-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_component_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
