# Generated by Django 3.0.6 on 2020-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_box_box_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_size',
            field=models.CharField(choices=[('60х60х40', 'Small'), ('m', 'Medium'), ('l', 'Large')], max_length=20),
        ),
    ]
