# Generated by Django 3.0.6 on 2020-09-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20200916_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_big_size',
            field=models.CharField(choices=[('240х185х120', '240х185х120'), ('270х220х70', '270х220х70')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='box_size',
            field=models.CharField(choices=[('50х50х35', '50х50х35'), ('60х60х40', '60х60х40'), ('80х80х40', '80х80х40')], max_length=20),
        ),
    ]
