# Generated by Django 3.0.6 on 2020-09-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0027_auto_20200916_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box_big',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_big_size', models.CharField(choices=[('240х185х120', '240х185х120'), ('270х220х70', '270х220х70')], max_length=20)),
                ('tirazh', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='box',
            name='box_big_size',
        ),
    ]
