# Generated by Django 3.0.6 on 2020-09-16 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_auto_20200916_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box_big',
            old_name='box_big_size',
            new_name='box_size',
        ),
    ]
