# Generated by Django 3.0.6 on 2020-09-16 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0029_auto_20200916_0858'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Box_big',
            new_name='BBox',
        ),
    ]
