# Generated by Django 3.0.6 on 2020-09-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20200916_0906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BBox',
            new_name='Box1',
        ),
    ]
