# Generated by Django 3.0.6 on 2020-09-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0031_auto_20200917_1221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box1',
            old_name='box_size',
            new_name='box_size1',
        ),
        migrations.RenameField(
            model_name='box1',
            old_name='tirazh',
            new_name='tirazh1',
        ),
    ]
