# Generated by Django 3.0.6 on 2020-09-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20200921_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='box',
            name='box_size',
            field=models.CharField(choices=[('50х50х35', '50х50х35'), ('60х60х40', '60х60х40'), ('60х60х40-P', '60х60х40-P'), ('80х80х40', '80х80х40'), ('80х80х40-P', '80х80х40-P'), ('240х185х120', '240х185х120'), ('270х220х70', '270х220х70')], default='80х80х40', max_length=20),
        ),
        migrations.AlterField(
            model_name='box1',
            name='box_size1',
            field=models.CharField(choices=[('240х185х120', '240х185х120'), ('270х220х70', '270х220х70')], default='80х80х40', max_length=20),
        ),
    ]
