

      version: '3'
      services:
        db:
          image: postgres
          POSTGRES_HOST_AUTH_METHOD=trust
        web:
          build: .
          command: python manage.py runserver 0.0.0.0:8080
          volumes:
            - .:/code
          environment:
            - DEBUG=1
          
              #- POSTGRES_PASSWORD=12345
          #POSTGRES_HOST_AUTH_METHOD: trust
          #-e POSTGRES_PASSWORD=12345
        
          #POSTGRES_VERSION=12.4 docker-compose up db
          ports:
            - "8080:8080"
          depends_on:
            - db
         
       


            